### PR TITLE
Unfortunate project name

### PR DESCRIPTION
**Pull request by watson**
GitHub Issues have unfortunately been disabled on this repo, and there doesn't seem to be any contact info anywhere - not here or on @jan-wassenberg's personal profile. So I'll do something really odd and submit this as a PR instead. I feel pretty dirty already 😅  

Though quite amusing for Danes, you might wanna consider another name for this format: https://translate.google.com/translate#da/en/pik

### CODE REVIEW

**Comment by styfle** [comment]
It's probably pronounced "pick" which is commonly spelled [pic](https://www.google.com/search?q=pic)

**Comment by KeizerDev** [comment]
Same for Dutch (https://translate.google.com/#nl/en/pik)

**Comment by jan-wassenberg** [comment]
Thanks, we have now enabled issues for this repository. Would you kindly file one for this?

**Comment by watson** [comment]
@jan-wassenberg thanks 😃 I've opened an issue now: #6

**Pull request closed without merging**
